In [1]:
import pandas as pd

In [12]:
dataset = pd.read_csv(r'C:\Users\PICHAU\PycharmProjects\Pandas\db.csv', sep=';', index_col=0)

In [13]:
for item in dataset:
    print(item)

Motor
Ano
Quilometragem
Zero_km
Acessórios
Valor

In [14]:
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [16]:
for index, row in dataset.iterrows():
    if (2019 - row['Ano']) != 0:
        dataset.loc[index, 'Km_media'] = row['Quilometragem']/(2019-row['Ano'])
    else:
        dataset.loc[index, 'Km_media'] = 0

In [19]:
dataset.isna()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
Jetta Variant,False,False,False,False,False,False,False
Passat,False,False,False,False,False,False,False
Crossfox,False,False,False,False,False,False,False
DS5,False,False,True,False,False,False,False
Aston Martin DB4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
Phantom 2013,False,False,False,False,False,False,False
Cadillac Ciel concept,False,False,False,False,False,False,False
Classe GLK,False,False,False,False,False,False,False
Aston Martin DB5,False,False,False,False,False,False,False
Macan,False,False,False,False,False,False,False